### ISSUE TITLE
Site Analyzer shows "Oops! Something went wrong." on a brand new New Relic account

### ISSUE THREAD

**Issue by junghex** [newrelic/nr1-browser-analyzer#58]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. ) 

Created a brand new account on New Relic and took all the necessary steps to install java script based Site Analyzer from the New Relic global catalog. Everything was working fine the first day. Came back to the console the next day, and all I can see is this message "Oops! Something went wrong."

[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )

I should be able to see graphs and other info as I did the first day.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used:
* Browser name and version: Tried both Brave (Version 1.15.72 Chromium: 86.0.4240.75 (Official Build) (x86_64))  and Firefox (81.0.1 (64-bit)) browsers 
* Operating System and version: MacOS Catalina (10.15.7 (19H2))

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by danielgolden** [comment]
Hi, @junghex. Sorry for the delay, can you provide the errors that appear in the console of Chrome Devtools? That be very helpful to diagnose exactly what's going wrong.

1. Right click on the page and click **"Inspect"**
2. Click on **"Console"**
3. Copy all of the text that appears in red and paste it as a reply to this thread.

**Comment by harshunifi** [comment]
I am facing the same issue in my SPA app. This is the console log output.

```
The above error occurred in the <Context.Consumer> component:
    in Breakdown (at wrapper.js:33)
    in NerdGraphQuery (created by ForwardRef(native))
    in Wrapper (at browser-analyzer-nerdlet/index.js:10)
    in BrowserAnalyzerNerdlet (created by Context.Consumer)
    in a
    in e

React will try to recreate this component tree from scratch using the error boundary you provided, e.

Warning: e: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```

**Comment by junghex** [comment]
Hi Team,

This is what I get:

Uncaught TypeError: t.settings is null
    c
https://nr3.nr-ext.net/artifact-index-production/e782da4a-7e4b-46db-8b1b-bb7c45a07877/1.3.5/shared~e782da4a-7e4b-46db-8b1b-bb7c45a07877--details~e782da4a-7e4b-46db-8b1b-bb7c45a07877--root.js
:1
    value
https://nr3.nr-ext.net/artifact-index-production/e782da4a-7e4b-46db-8b1b-bb7c45a07877/1.3.5/shared~e782da4a-7e4b-46db-8b1b-bb7c45a07877--details~e782da4a-7e4b-46db-8b1b-bb7c45a07877--root.js
:1
    React 16
    m
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    t
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    c
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    _invoke
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    e
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    n
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    a
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    exports
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    exports
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    bzYt
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    n
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    <anonymous>
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    <anonymous>
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
shared~e782da4a-7e4b-46db-8b1b-bb7c45a07877--details~e782da4a-7e4b-46db-8b1b-bb7c45a07877--root.js
:1:32150
<https://nr3.nr-ext.net/artifact-index-production/e782da4a-7e4b-46db-8b1b-bb7c45a07877/1.3.5/shared~e782da4a-7e4b-46db-8b1b-bb7c45a07877--details~e782da4a-7e4b-46db-8b1b-bb7c45a07877--root.js>

The above error occurred in the <Context.Consumer> component: in n in
NerdGraphQuery (created by ForwardRef(native)) in n (created by n) in n
(created by Context.Consumer) in a in e React will try to recreate this
component tree from scratch using the error boundary you provided, e.
react-dom.development.js:15873:13
<https://d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js>

Warning: e: Error boundaries should implement getDerivedStateFromError().
In that method, return a state update to display an error message or
fallback UI. react-dom.development.js:500:32
<https://d1zobbh8kytrtv.cloudfront.net/lib/react/16.6.3/react-dom.development.js>
    React 19
    m
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    t
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    c
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    _invoke
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    e
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    n
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    a
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    exports
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    exports
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    value
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    bzYt
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    n
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    <anonymous>
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1
    <anonymous>
https://d1zobbh8kytrtv.cloudfront.net/platform/wanda--wanda-ec-ui--third-party-sdk-release-1613.js
:1

**Comment by danielgolden** [comment]
@harshunifi @junghex Thanks again for bringing this up. I am able to reproduce this issue am working on this today. Hope to have an update for you very soon. Sorry for the trouble :/.

**Comment by danielgolden** [comment]
@harshunifi @junghex We've just merged in [a fix](https://github.com/newrelic/nr1-browser-analyzer/pull/62) that addresses the problem on our end. Can you check this out and see if it resolved the issue for you too?

**Comment by junghex** [comment]
Hi Daniel,

No, it is still not working for me. Sorry for the bad news ;)

**Comment by harshunifi** [comment]
@danielgolden it has started working for me. Thank you for providing the fix :)

@junghex try recloning the repo with the initial steps and see if it works.

```
nr1 nerdpack:clone -r https://github.com/newrelic/nr1-browser-analyzer.git
cd nr1-browser-analyzer
nr1 nerdpack:serve
```

**Comment by danielgolden** [comment]
@harshunifi Glad to hear it's working well now! Thanks for following up :). Credit to @tangollama for the fix.
@junghex If it doesn't work after following the steps listed above, please lmk.

**Comment by junghex** [comment]
Yay! It's working now! Thanks so much for fixing it!

**Comment by tangollama** [comment]
Closing with the release of #62.
